/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PanelHeader {
        /**
          * Header title
         */
        "headerTitle": string;
        /**
          * Header subtitle
         */
        "subtitle": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPanelHeaderElement extends Components.PanelHeader, HTMLStencilElement {
    }
    var HTMLPanelHeaderElement: {
        prototype: HTMLPanelHeaderElement;
        new (): HTMLPanelHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "panel-header": HTMLPanelHeaderElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PanelHeader {
        /**
          * Header title
         */
        "headerTitle"?: string;
        /**
          * Header subtitle
         */
        "subtitle"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "panel-header": PanelHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "panel-header": LocalJSX.PanelHeader & JSXBase.HTMLAttributes<HTMLPanelHeaderElement>;
        }
    }
}
